### PR TITLE
Fixed Julia 0.6 deprecations

### PR DESCRIPTION
**Pull request by RobertRosca**
Just updated the code a bit to fix the deprecation warnings that come up in Julia 0.6.0.

Haven't changed `.travis.yml`'s value for Julia to 0.6 since I don't know how it works or if anything else has to be changed to get it to work.

### CODE REVIEW

**Comment by pjabardo** [comment]
Thanks a lot! I was going to do that this weekend and you saved me a couple of hour of work.

Paulo

**Comment by lwabeke** [comment]
Any chance that you can also step to a new package release? (I find it slightly nicer to just be able to use the release instead of doing a checkout of master)

I believe it would be changing the minor version number, since the requirement of the julia version has changed:
PkgDev.tag("CurveFit", :minor)
PkgDev.publish()

**Comment by pjabardo** [comment]
I will do it this week end. I promise!

Paulo
 

    Em sexta-feira, 2 de março de 2018 07:28:12 BRT, Leon Wabeke <notifications@github.com> escreveu:  
 
 
Any chance that you can also step to a new package release? (I find it slightly nicer to just be able to use the release instead of doing a checkout of master)

I believe it would be changing the minor version number, since the requirement of the julia version has changed:
PkgDev.tag("CurveFit", :minor)
PkgDev.publish()

**Comment by pjabardo** [comment]
I did some work but there is a problem on Polynomials.jl. Anything not using Poly appears to be working. I will try to solve the Polynomials.jl issues tonight or tomorrow.
Paulo
 

    Em sexta-feira, 2 de março de 2018 07:28:12 BRT, Leon Wabeke <notifications@github.com> escreveu:  
 
 
Any chance that you can also step to a new package release? (I find it slightly nicer to just be able to use the release instead of doing a checkout of master)

I believe it would be changing the minor version number, since the requirement of the julia version has changed:
PkgDev.tag("CurveFit", :minor)
PkgDev.publish()

**Pull request merged**
